[project]
name = "beatwatch_process"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Maya", email = "mayabflannery@gmail.com" }]
requires-python = ">=3.13"
dependencies = [
  "datashader>=0.18.2",
  "hvplot>=0.12.1",
  "loguru>=0.7.3",
  "pandas>=2.3.3",
  "pandas-stubs>=2.3.2.250926",
  "pytz>=2025.2",
  "scipy>=1.16.2",
  "scipy-stubs>=1.16.2.4",
  "statsmodels>=0.14.6",
]

[tool.uv.sources]
beatwatch_process = { path = "src/beatwatch_process" }

[project.scripts]
beatwatch-process = "beatwatch_process:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["beatwatch_process"]


[tool.ruff]
line-length = 80
[tool.ruff.lint]
extend-select = ["I"]
[tool.ruff.format]
quote-style = "double"
docstring-code-format = true


[tool.basedpyright]
typeCheckingMode = "standard"
pythonVersion = "3.13"
extraPaths = ["src"]



[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.1",
    "ruff>=0.14.9",
]
